name: Regression End-to-end tests

on:
  push:
    branches:
      - main

jobs:
  Add-To-Cart-flow-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run Add-To-Cart
        uses: cypress-io/github-action@v6
        with:
          command-prefix: npx run
          command: npx run test:registerTest

  Reg-flow-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run RegisterTest
        uses: cypress-io/github-action@v6
        with:
          command-prefix: npx run
          command: npx run test:addtocart
